sudo: required
services:
  - docker

before_install:
  - docker build -t privatebutts/pipeline-client-dev -f Dockerfile.dev .

script:
  - docker run -e CI=true privatebutts/pipeline-client-dev npm run test